name: 'Assume Repo Role'
description: 'Assumes an AWS IAM role based on repository name, configuring AWS credentials for subsequent workflow steps'

inputs:
  AWS_REGION:
    description: 'The AWS region to use for all AWS API calls'
    required: true
    default: 'us-east-1'
  AWS_ACCOUNT_NAME:
    description: 'AWS Account identifier to deploy to, used to look up appropriate role ARN in secrets'
    required: false
    default: 'corp-delivery-prod'

runs:
  using: "composite"
  steps:
    - name: Get repo and secret name
      shell: bash
      run: |
        REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2 | tr '[:lower:]' '[:upper:]' | tr '-' '_')
        echo "REPO=$REPO" >> $GITHUB_ENV

    - name: Set region
      shell: bash
      run: |
        echo "AWS_REGION=${{ inputs.AWS_REGION }}" >> $GITHUB_ENV

    - name: Get repo roles
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          ,${{ inputs.AWS_ACCOUNT_NAME }}/gha-aws-auth
        parse-json-secrets: true

    - name: Set role ARN
      shell: bash
      run: |
        ROLE_ARN=$(printenv $REPO)
        echo "ROLE_ARN=$ROLE_ARN" >> $GITHUB_ENV

    - name: Configure AWS credentials Repo Role
      uses: aws-actions/configure-aws-credentials@main
      with:
        role-to-assume: ${{ env.ROLE_ARN }}
        aws-region: ${{ inputs.AWS_REGION }}
        mask-aws-account-id: false
        role-chaining: true
        role-skip-session-tagging: true