name: Run Ansible Deploy

on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: true
        type: string
      AWS_ROLE:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      DEPLOY_FILE:
        required: false
        type: string
      VARS:
        required: false
        type: string
      ANSIBLE_VARS:
        required: false
        type: string
      PLAYBOOK:
        required: false
        type: string
      VERBOSE:
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  ansible:
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Install Node
        shell: bash
        run: |
          curl -sS https://webi.sh/node | sh
          echo ~/.local/opt/node/bin >> $GITHUB_PATH

      - name: Git clone the repository
        uses: actions/checkout@v4.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ inputs.AWS_ROLE }}
          aws-region: ${{ inputs.AWS_REGION }}
          mask-aws-account-id: false
        id: aws_login

      - name: Export Script ENV
        if: ${{ inputs.VARS }}
        shell: bash
        run: |
          echo "${{ inputs.VARS }}" >> $GITHUB_ENV

      - name: Run Ansible Deploy Script
        if: ${{ inputs.DEPLOY_FILE != '' }}
        shell: bash
        run: ${{ inputs.DEPLOY_FILE }}

      - name: Get Ansible vault password
        if: ${{ inputs.PLAYBOOK != '' }}
        uses: say8425/aws-secrets-manager-actions@v2.2.1
        with:
          SECRET_NAME: ansible-vault-password
          AWS_DEFAULT_REGION: eu-west-1
          OUTPUT_PATH: .env

      - name: Run playbook
        if: ${{ inputs.PLAYBOOK != '' }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{ inputs.PLAYBOOK }}
          directory: ./
          vault_password: ${{ env.ANSIBLE_VAULT_PASSWORD }}
          options: |
            --extra-vars "${{ inputs.ANSIBLE_VARS }}"
            "${{ inputs.VERBOSE }}"
