name: Run Deploy File

on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: true
        type: string
      AWS_ROLE:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      SYSTEM_ENVIRONMENT:
        required: true
        type: string
      DEPLOY_FILE:
        required: false
        type: string
      VARS:
        required: false
        type: string
      PLAYBOOK:
        required: false
        type: string
      VERBOSE:
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  run_ansible:
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update -y && sudo apt-get install -y \
          curl wget unzip jq
          curl -sS https://webi.sh/node | sh
          echo ~/.local/opt/node/bin >> $GITHUB_PATH

      - name: Git clone the repository
        uses: actions/checkout@v4.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ inputs.AWS_ROLE }}
          aws-region: ${{ inputs.AWS_REGION }}
          mask-aws-account-id: false
        id: aws_login

      - name: Run Ansible Deploy Script
        if: ${{ inputs.DEPLOY_FILE != '' }}
        shell: bash
        run: ${{ inputs.DEPLOY_FILE }}
        env:
          VARS: ${{ inputs.VARS }}

      - name: Run playbook
        if: ${{ inputs.DEPLOY_FILE == '' }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{ inputs.PLAYBOOK }}
          directory: ./
          vault_password: ${{env.ANSIBLE_VAULT_PASSWORD}}
          options: |
            --extra-vars "${{ inputs.VARS }}"
            "${{ inputs.VERBOSE }}"
