name: Run Ansible Deploy

on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: true
        type: string
      AWS_ACCOUNT_NAME:
        type: string
        required: false
        default: 'corp-delivery-prod'
      AWS_ALTERNATIVE_ROLE:
        required: false
        type: string
      AWS_REGION:
        required: true
        type: string
      DEPLOY_FILE:
        required: false
        type: string
      VARS:
        required: false
        type: string
      ANSIBLE_VARS:
        required: false
        type: string
        default: ''
      ANSIBLE_SECRET:
        required: false
        type: string
        default: ''
      PLAYBOOK:
        required: false
        type: string
      VERBOSE:
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  ansible:
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4.1.0

      - name: Configure AWS credentials
        uses: 2uinc/gha-workflows/.github/actions/assume_repo_role@main
        with:
          AWS_REGION: ${{ inputs.AWS_REGION }}
          AWS_ACCOUNT_NAME: ${{ inputs.AWS_ACCOUNT_NAME }}
          AWS_ALTERNATIVE_ROLE: ${{ inputs.AWS_ALTERNATIVE_ROLE }}

      - name: Export Script ENV
        if: ${{ inputs.VARS }}
        shell: bash
        run: |
          echo "${{ inputs.VARS }}" >> $GITHUB_ENV

      - name: Run Ansible Deploy Script
        if: ${{ inputs.DEPLOY_FILE != '' }}
        shell: bash
        run: ${{ inputs.DEPLOY_FILE }}

      - name: Get Ansible vault password
        if: ${{ inputs.ANSIBLE_SECRET != '' }}
        uses: say8425/aws-secrets-manager-actions@v2.2.1
        with:
          SECRET_NAME: ${{ inputs.ANSIBLE_SECRET }}
          AWS_DEFAULT_REGION: eu-west-1
          OUTPUT_PATH: .env

      - name: Run playbook
        if: ${{ inputs.PLAYBOOK != '' && inputs.ANSIBLE_VARS == '' }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{ inputs.PLAYBOOK }}
          directory: ./
          vault_password: ${{ env.ANSIBLE_VAULT_PASSWORD }}
          options: |
            "${{ inputs.VERBOSE }}"

      - name: Run playbook with extra vars
        if: ${{ inputs.PLAYBOOK != '' && inputs.ANSIBLE_VARS != '' }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{ inputs.PLAYBOOK }}
          directory: ./
          vault_password: ${{ env.ANSIBLE_VAULT_PASSWORD }}
          options: |
            --extra-vars "${{ inputs.ANSIBLE_VARS }}"
            "${{ inputs.VERBOSE }}"
