name: Run Deploy File

on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: true
        type: string
      AWS_ACCOUNT_NAME:
        required: true
        type: string
      AWS_ALTERNATIVE_ROLE:
        required: false
        type: string
      AWS_REGION:
        required: true
        type: string
      DEPLOY_FILE:
        required: true
        type: string
      VARS:
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  run_script:
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4.1.0

      - name: Export extra vars
        if: ${{ inputs.VARS }}
        shell: bash
        run: |
          echo "${{ inputs.VARS }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: getsmarter/gha-workflows/.github/actions/assume_repo_role@runner-switch
        with:
          AWS_REGION: ${{ inputs.AWS_REGION }}
          AWS_ACCOUNT_NAME: ${{ inputs.AWS_ACCOUNT_NAME }}
          AWS_ALTERNATIVE_ROLE: ${{ inputs.AWS_ALTERNATIVE_ROLE }}

      - name: Run Deploy Script
        shell: bash
        run: ${{ inputs.DEPLOY_FILE }}
