name: Run Deploy File

on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: true
        type: string
      AWS_ACCOUNT_NAME:
        type: string
        required: false
        default: 'corp-delivery-prod'
      AWS_REGION:
        required: true
        type: string
      DEPLOY_FILE:
        required: true
        type: string
      VARS:
        required: false
        type: string
      IMAGE:
        required: false
        type: string
        default: ''

permissions:
  id-token: write
  contents: read

jobs:
  run_script_container:
    if: ${{ inputs.IMAGE }}
    runs-on: ${{ inputs.RUNS_ON }}
    container:
      image: ${{ inputs.IMAGE }}
      env:
        AWS_CONTAINER_CREDENTIALS_FULL_URI: http://169.254.170.23/v1/credentials
        AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE: /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
        AWS_ROLE_ARN: arn:aws:iam::823386275404:role/${GITHUB_REPOSITORY_OWNER}-gha-mgmt-default
      volumes:
        - /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token:/var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4.1.0

      - name: Export extra vars
        if: ${{ inputs.VARS }}
        shell: bash
        run: |
          echo "${{ inputs.VARS }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: 2uinc/gha-workflows/.github/actions/assume_repo_role@main
        with:
          AWS_REGION: ${{ inputs.AWS_REGION }}
          AWS_ACCOUNT_NAME: ${{ inputs.AWS_ACCOUNT_NAME }}

      - name: Run Deploy Script
        shell: bash
        run: ${{ inputs.DEPLOY_FILE }}
  

  run_script:
    if: ${{ inputs.IMAGE == '' }}
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4.1.0

      - name: Export extra vars
        if: ${{ inputs.VARS }}
        shell: bash
        run: |
          echo "${{ inputs.VARS }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: 2uinc/gha-workflows/.github/actions/assume_repo_role@main
        with:
          AWS_REGION: ${{ inputs.AWS_REGION }}
          AWS_ACCOUNT_NAME: ${{ inputs.AWS_ACCOUNT_NAME }}

      - name: Run Deploy Script
        shell: bash
        run: ${{ inputs.DEPLOY_FILE }}