name: Run Deploy File

on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: true
        type: string
      AWS_ROLE:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      DEPLOY_FILE:
        required: true
        type: string
      VARS:
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  run_script:
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4.1.0

      - name: Export extra vars
        if: ${{ inputs.VARS }}
        shell: bash
        run: |
          echo "${{ inputs.VARS }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ inputs.AWS_ROLE }}
          aws-region: ${{ inputs.AWS_REGION }}
          mask-aws-account-id: false
          role-chaining: true
          role-skip-session-tagging: true
        id: aws_login

      - name: Run Deploy Script
        shell: bash
        run: ${{ inputs.DEPLOY_FILE }}
